Code/MuseumApp/MuseumApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('', include('museum.urls')),


    path('admin/', admin.site.urls, name='admin'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Code/MuseumApp/museum/urls.py
from django.urls import include, path, re_path
import museum.views
from .views import APIView, AgeView, ExtendsTestView, PrototypeTestView, ReviewListView, ReviewDetailView, ReviewCreateView, ReviewDeleteView, SoldierTaskView, TableWithJavaScriptView, lab_taskView

urlpatterns = [

    path('', museum.views.HomeView.as_view(), name='home'),
    path('home/', museum.views.HomeView.as_view(), name='home'),
    path('about/', museum.views.about, name='about'),
    path('hall/', museum.views.HallListView.as_view(), name='hall'),
    path('excursion/', museum.views.ExcursionListView.as_view(), name='excursion'),
    path('exposition/', museum.views.ExpositionListView.as_view(), name='exposition'),
    path('exhibition/', museum.views.ExhibitionListView.as_view(), name='exhibition'),
    path('hall/exhibits/<int:id>/', museum.views.HallExibitDetailView.as_view(),name='hall_exhibits'),
    path('exposition/exhibits/<int:id>/', museum.views.ExpositionExibitDetailView.as_view(),name='exposition_exhibits'),
    path('exhibition/exhibits/<int:id>/', museum.views.ExhibitionExibitDetailView.as_view(),name='exhibition_exhibits'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/',museum.views.UserAccountView.as_view(), name='user_account' ),
    path('user/exhibits/', museum.views.EmployeeExhibitDetailView.as_view(),name='user_exhibits'),
    path('info/', museum.views.InfoView.as_view(), name='info'),
    path('diagram/', museum.views.DiagramView.as_view(), name='diagram'),
    path("articles/", museum.views.ArticlesListView.as_view(), name="article-list"),
    path("article/<int:pk>/", museum.views.ArticleDetailView.as_view(), name="article-detail"),
    path("faq/", museum.views.FAQView.as_view(), name="faq"),
    path("contacts/", museum.views.EmployeeListView.as_view(), name="contacts"),
    path("privacy/", museum.views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("vacancy/", museum.views.VacancyListView.as_view(), name="vacancy-list"),
    path("vacancy/<int:pk>/", museum.views.VacancyDetailView.as_view(), name="vacancy-detail"),
    path("promocodes/", museum.views.PromocodeView.as_view(), name="promocodes"),
    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('reviews/create/', ReviewCreateView.as_view(), name='review_create'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('reviews/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),
    path('tasks_kabs/', lab_taskView.as_view(), name='lab_task'),
    path('api/', APIView.as_view(), name='api'),
    path('soldiertask/', SoldierTaskView.as_view(), name='soldier_task'),
    path('age/', AgeView.as_view(), name='age'),
    path('tablejs/', TableWithJavaScriptView.as_view(), name='table'),
    path('extends/', ExtendsTestView.as_view(), name='extends'),
    path('prototypes/', PrototypeTestView.as_view(), name='prototype'),

]

Code/MuseumApp/museum/models.py
from xmlrpc.client import DateTime
from django.core import validators
from django.core.validators import MinLengthValidator
from django.db import models
from datetime import datetime
from django.core.validators import RegexValidator

class Hall(models.Model):

    number = models.CharField(max_length=3, help_text="Enter hall number")

    name = models.CharField(max_length=20, help_text="Enter hall name")

    floor = models.CharField(max_length=3, help_text="Enter hall floor")

    area = models.PositiveIntegerField(help_text="Enter hall area")

    def __str__(self):
        return self.name




class Position(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a position")

    def __str__(self):
        return self.name



from phonenumber_field.modelfields import PhoneNumberField

class Employee(models.Model):

    user_name = models.CharField(max_length=20, help_text="Enter user name")
    
    photo = models.ImageField(upload_to="images/profile_photos/", help_text="Enter profile photo")

    first_name = models.CharField(max_length=20, help_text="Enter full name")

    last_name = models.CharField(max_length=20, help_text="Enter last name")

    hall = models.ForeignKey('Hall', on_delete=models.CASCADE, related_name="employee")

    num_validator = RegexValidator(regex=r"^\+375 \(29\) \d{3}-\d{2}-\d{2}$")

    phone_number = models.CharField(max_length=20, validators=[num_validator], default='+375 (29) xxx-xx-xx')

    position = models.ForeignKey('Position', on_delete=models.CASCADE,related_name="employee")

    def __str__(self):
        return f"{self.last_name} {self.position}"



import uuid
from django.core.validators import MaxValueValidator, MinValueValidator 

class Excursion(models.Model):

    excursion_code = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular excursion")

    name = models.CharField(max_length=20, help_text="Enter excursion name")

    date = models.DateField()

    group_amount = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])

    guide = models.OneToOneField('Employee', on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class ArtForm(models.Model):
    name = models.CharField(max_length=20, help_text="enter art form")

    def __str__(self):
        return self.name




class Exhibit(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular exhibit")

    name = models.CharField(max_length=20, help_text="enter Xzibit name")

    art_form = models.ManyToManyField('ArtForm')

    admission_date = models.DateField()

    observer = models.ForeignKey('Employee',on_delete=models.DO_NOTHING, related_name="exhibit")

    photo = models.URLField(default='')

    hall = models.ForeignKey('Hall', on_delete=models.CASCADE, related_name="exhibit")

    exposition = models.ForeignKey('Exposition', on_delete=models.DO_NOTHING, related_name="exhibit", null=True, blank=True)

    exhibition = models.ForeignKey('Exhibition', on_delete=models.DO_NOTHING, related_name="exhibit", null=True, blank=True)

    def display_art_form(self):
        return ', '.join([ art_form.name for art_form in self.art_form.all()[:3] ])
    display_art_form.short_description = 'Art form'

    def __str__(self):
        return self.name

class Exposition(models.Model):
    name = models.CharField(max_length=20, help_text="enter exposition name")

    theme = models.ForeignKey('Theme', on_delete=models.CASCADE, related_name="exposition")

    hall = models.ManyToManyField('Hall')

    def __str__(self):
        return self.name
    



class Exhibition(models.Model):
    name = models.CharField(max_length=20, help_text="enter exhibition name")

    theme = models.ForeignKey('Theme', on_delete=models.CASCADE, related_name="exhibition")

    hall = models.ManyToManyField('Hall')

    date = models.DateField()

    def __str__(self):
        return self.name
    


class Theme(models.Model):
    name = models.CharField(max_length=20, help_text="enter exposition name")

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=100, help_text="enter title of the article")
    
    summury = models.TextField(max_length=500, help_text="enter summury of the article")
    
    image =  models.ImageField(upload_to="images/article_photos/", help_text="Enter article photo")
    
    content = models.TextField(help_text="enter content of the article")
    
    creation_date = models.DateTimeField(auto_now_add=True)
    
class Vacancy(models.Model):
    
    position = models.CharField(max_length=50, help_text="enter employee position")

    company_name = models.CharField(max_length=50, help_text="enter company name")
    
    city = models.CharField(max_length=50, help_text="enter city")
    
    job_character = models.CharField(max_length=50, help_text="enter job character")
    
    schedule = models.CharField(max_length=50, help_text="enter schedule")
    
    employment = models.CharField(max_length=50, help_text="enter employement")
    
    experience = models.CharField(max_length=50, help_text="enter experience")
    
    education = models.CharField(max_length=50, help_text="enter education")
    
    description = models.TextField(help_text="enter vacancy description")
    
    salary = models.CharField(max_length=50, help_text="enter salary")
    
    def __str__(self):
        return f"{self.position} {self.company_name}"
    
class Review(models.Model):
    reviewer = models.CharField(max_length=50, help_text="enter reviewer")
    
    rate = models.PositiveIntegerField(validators=[validators.MinValueValidator(1),validators.MaxValueValidator(10)], help_text="enter rate")
    
    text = models.TextField(help_text="enter review text")
    
    creation_date = models.DateTimeField(auto_now_add=True)
    
    will_come_back = models.BooleanField(default=False);
    
class Promocode(models.Model):
    code = models.CharField(max_length=50, help_text="enter Promocode")
    
    start_date = models.DateTimeField()

    expiration_date = models.DateTimeField()
    
    def __str__(self):
        return self.code
    

Code/MuseumApp/museum/forms.py
# forms.py
from dataclasses import fields
from datetime import date
import logging
from typing import Any, Dict
from django import forms
from django.core import validators

from museum.models import Employee, Exhibit, Exhibition, Hall, Promocode, Review

logger = logging.getLogger(__name__)

class ExhibitForm(forms.ModelForm):

    def clean(self):
            admission_date = self.cleaned_data.get('admission_date')
            hall = self.cleaned_data.get('hall')
            observer = self.cleaned_data.get('observer')
            exhibition = self.cleaned_data.get('exhibition')

            if admission_date > date.today():
                logger.error(f'Failed to create exhibit - admission date are incorrect')
                raise forms.ValidationError("Admission date are incorrect")
            
            if hall != observer.hall:
                logger.error(f'Failed to create exhibit - exhibit hall and observer hall are different')
                raise forms.ValidationError("Exhibit hall and observer hall are different")
            
            if exhibition and exhibition.date < admission_date:
                logger.error(f'Failed to create exhibit - admission date are greater then exhibition date')
                raise forms.ValidationError("Admission date are greater then exhibition date")
            
            logger.info(f'user input passed custom validation')
            
            return self.cleaned_data
    
    class Meta:
         model = Exhibit
         fields = '__all__'

class PromocodeForm(forms.ModelForm):
    def clean(self):
        start_date = self.cleaned_data.get('start_date')

        expiration_date = self.cleaned_data.get('expiration_date')
        
        if (start_date > expiration_date):
            raise forms.ValidationError("Invalid promocode start and expiration dates") 
        
        return self.cleaned_data
    
    class Meta:
         model = Promocode
         fields = '__all__'

class ReviewForm(forms.Form):
    reviewer = forms.CharField(max_length=50)
     
    rate = forms.IntegerField(validators=[validators.MinValueValidator(1),validators.MaxValueValidator(10)])
    
    text = forms.CharField()
    
    will_come_back = forms.BooleanField(required=False  )
        

    

Code/MuseumApp/museum/templates/museum/about.html
{% extends "shared/layout.html" %}

{% block content %}
<section id="top" class="slide cert">
    <img src="/media/images/leftDoor.jpg" id="door_left" class="slide" />
    <img src="/media/images/rightDoor.jpg" id="door_right" class="slide" />
</section>
<article>
    <h4>Introduction</h4>

    In the world of museums, the name <em>"Smithsonian Institution"</em> reigns supreme. Let's embark on a<wbr /> condensed journey through the history of this institution that has redefined how we experience<wbr /> and cherish art, culture, and history.

    <h5>The Visionary Beginning</h5>

    Our story begins in the late 19th century when curator John A. Smithson envisioned a museum <wbr /><em>accessible to everyone</em>. In 1879, he founded the "Smithsonian Institution," named after his <wbr />family, becoming the cornerstone of the company that would rule the museum scene.

    <h5>Innovation and Expansion</h5>

    The Smithsonian rapidly grew into a network of museums, research centers, and libraries,<wbr /> championing innovation and excellence. <em>Interactive exhibits</em>, <em>immersive displays</em>, and <em>cutting-edge<wbr /> technology</em> reshaped the museum experience, making the Smithsonian a <em>global leader</em> in the field.

    <h5>Global Influence</h5>

    The Smithsonian's influence extended worldwide. Collaborations with international museums<wbr /> promoted cross-cultural understanding, reinforcing its position as a company shaping not only<wbr /> museums but international cooperation and arts appreciation.

    <h5>Adaptation and Challenges</h5>

    Facing economic shifts and technological advances, the Smithsonian adapted by investing in<wbr /> conservation, sustainability, and cutting-edge technologies like VR and AR, ensuring its<wbr /> continued prominence.

    <h5>Conclusion</h5>

    The Smithsonian Institution's journey, from its visionary beginnings to its global impact, is a<wbr /> testament to its commitment to education and culture. As we explore its museums and digital<wbr /> archives, we appreciate its legacy and its enduring rule over the world of museums.

</article>
<br />
<article>
    <ul>
        <li>
            1879 - foundation
        </li>
        <li>
            1889 - local fame
        </li>
        <li>
            1899 - local monopolist
        </li>
        <li>
            1908 - global fame
        </li>
        <li>
            1918 - global monopolist
        </li>
        <li>
            1928 - game is completed
        </li>
    </ul>
</article>
<img src="/media/icons/logos/MuseumLogo.png" alt="breathtakin logo of brilliant company"
     sizes="(max-width: 1em) 1em, 2em"
     srcset="/media/icons/logos/MuseumLogo.png 1.33x,
          /media/icons/logos/MuseumLogoHighRes.png 2.67x,
          /media/icons/logos/MuseumLogoHighResUltra.png 4x"
     class="logo">
<br />

{%include "shared/sertificate.html"%}
<br />

{% endblock %}

{%load static%}
{% block scripts%}
<script type="text/javascript" src="{% static 'js/ScrollingAnimation.js' %}"></script>
{%endblock%}

Code/MuseumApp/museum/templates/museum/exhibition.html
{% extends "shared/layout.html" %}

{% block content %}
<section class="grid-container">
    {% if exhibition_list %}

    {% for exhibition in exhibition_list %}
    <table border="1" class="grid-container-item">
        <thead>
            <tr>
                <th>Reference</th>
                <th>Information</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>exhibition name</td>
                <td>{{ exhibition.name }}</td>
            </tr>
            <tr>
                <td> theme </td>
                <td>{{ exhibition.theme }}</td>
            </tr>
            <tr>
                <td>date </td>
                <td>{{ exhibition.date }}</td>
            </tr>
            {%if exhibition.hall.all%}
            <tr>
                <td colspan="2">
                    Hall
                </td>
            </tr>
            {% for hall in exhibition.hall.all %}
            <tr>
                <td colspan="2">
                    {{hall}}

                </td>
            </tr>
            {% endfor %}
            {%else%}
            <tr>
                <td>
                    There are no halls
                </td>
            </tr>
            {% endif %}
            <tr>
                <td colspan="2">
                    <a href="exhibits/{{ exhibition.id }}">View exibits</a>
                </td>
            </tr>

        </tbody>
    </table>


    {% endfor %}

    {% else %}
    <p>There are no excursion</p>
    {% endif %}
</section>

<!--<section itemscope itemtype="Http://data-vocabulary.org/Event/">
    <h1>Exhibitions</h1>
    {% if exhibition_list %}
    <ul>

        {% for exhibition in exhibition_list %}
        <li itemprop="summary">
            Name: {{ exhibition.name }}
        </li>
        <li>
            Theme: {{ exhibition.theme }}
        </li>
        <li itemprop="startDate">
            Date: {{ exhibition.date }}
        </li>

        {%if exhibition.hall.all%}
        <li>
            Halls:
            <ul>
                {% for hall in exhibition.hall.all %}
                <li>
                    {{hall}}
                </li>
                {% endfor %}
            </ul>
        </li>
        {%else%}
        <li>
            There are no halls
        </li>
        {% endif %}
        <li>
            <a href="exhibits/{{ exhibition.id }}">View exibits</a>
            <hr />
        </li>




        {% endfor %}

    </ul>
    {% else %}
    <p>There are no exhibition</p>
    {% endif %}

</section>-->
{% endblock %}

Code/MuseumApp/museum/templates/museum/exposition.html
{% extends "shared/layout.html" %}

{% block content %}
<section class="grid-container">
    {% if exposition_list %}

    {% for exposition in exposition_list %}
    <table border="1" class="grid-container-item">
        <thead>
            <tr>
                <th>Reference</th>
                <th>Information</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>exposition name</td>
                <td>{{ exposition.name }}</td>
            </tr>
            <tr>
                <td> theme </td>
                <td>{{ exposition.theme }}</td>
            </tr>

            {%if exposition.hall.all%}
            <tr>
                <td colspan="2">
                    Hall
                </td>
            </tr>
                {% for hall in exposition.hall.all %}
            <tr>
                <td colspan="2">
                    {{hall}}

                </td>
            </tr>
            {% endfor %}
            {%else%}
            <tr>
                <td>
                    There are no halls
                </td>
            </tr>
            {% endif %}
            <tr>
                <td colspan="2">
                    <a href="exhibits/{{ exposition.id }}">View exibits</a>
                </td>
            </tr>

        </tbody>
    </table>


    {% endfor %}

    {% else %}
    <p>There are no excursion</p>
    {% endif %}
</section>

<!--<section>
    <h1>Expositions</h1>
    {% if exposition_list %}
    <ul>

        {% for exposition in exposition_list %}
        <li>
            Name: {{ exposition.name }}
        </li>
        <li>
            Theme: {{ exposition.theme }}
        </li>

        {%if exposition.hall.all%}
        <li>
            Halls:
            <ul>
                {% for hall in exposition.hall.all %}

                <li>
                    {{hall}}
                </li>

                {% endfor %}
            </ul>
        </li>
        {%else%}
        <li>
            There are no halls
        </li>
        {% endif %}
        <li>
            <a href="exhibits/{{ exposition.id }}">View exibits</a>
            <hr />
        </li>



        {% endfor %}

    </ul>
    {% else %}
    <p>There are no exposition</p>
    {% endif %}

</section>-->
{% endblock %}

Code/MuseumApp/museum/templates/museum/index.html
{% extends "shared/layout.html" %}

{% block content %}

<h1 class="banner" style="color:red">Warning!!!!!</h1>
<h3 style="color:red" id="countdown"></h3>
<br />
<div>
    <h2>Latest articles:</h2>
    {%for article in articles%}
    <article class="cards">
        <div class="card-wrapper cards">
            <div class="card cards">
                <h3 style=" position:relative; left: 40px; word-break:break-all; width:50vw;">{{ article.title }}</h3>
                <div class="content cards">
                    <p class="clip">{{ article.summury }}</p>
                    <img style="width: 50vw; height:50vh;" src="{{article.image.url}}" alt="Photo doesnt exist">
                    <br />
                    <a href="/article/{{article.pk}}">Reade more</a>
                </div>
            </div>
        </div>
    </article>
    {%endfor%}
    <aside>
        <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
            <img src="/media/images/addBanners/addBanner.png" alt="Advertisment banner" class="banner">
        </a>
    </aside>

</div>

{% endblock %}

{%load static%}
{% block scripts%}
<script type="text/javascript" src="{% static 'js/Countdown.js' %}"></script>
<script type="text/javascript" src="{% static 'js/Cards.js' %}"></script>
{%endblock%}

Code/MuseumApp/museum/templates/museum/info.html
{% extends "shared/layout.html" %}

{% block title %}Info{% endblock %}

{% block content %}
<h1>Static Info</h1>
<article>
    <table border="1">
        <caption>Statistics</caption>
        <tr>
            <th id="parameter">Parameter</th>
            <th id="count">Count</th>
            <th id="period">Period</th>
        </tr>
        <tr>
            <td headers="parameter">Count of hals</td>
            <td headers="count">{{ halls_count }}</td>
            <td headers="period">all time</td>
        </tr>
        <tr>
            <td headers="parameter">Count of exhibits</td>
            <td headers="count">{{ exhibits_count }}</td>
            <td headers="period">all time</td>
        </tr>
        <tr>
            <td headers="parameter">Count of exhibitions</td>
            <td headers="count">{{ exhibitions_count }}</td>
            <td headers="period">all time</td>
        </tr>
        <tr>
            <td headers="parameter">Count of expositions</td>
            <td headers="count">{{ expositions_count }}</td>
            <td headers="period">all time</td>
        </tr>
        <tr>
            <td headers="parameter">Count of excursions</td>
            <td headers="count">{{ this_month_excursion_count }}</td>
            <td headers="period">this month</td>
        </tr>
        <tr hidden>
            <td headers="parameter">Count of people, who where at excursions</td>
            <td headers="count" id="all_people_count">{{ all_people_count }}</td>
            <td headers="period">all time</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
    <br />
    <div>
        <div>
            <label>Coefficient of vanished people</label>
            <input type="number" min="1" max="10" id="DecreasingCoefficient" value="1" />
        </div>
        <button id="evaluateButton" onclick="EvaluateNumberOfPeople()">Evalueate</button>
    </div>
    <div id="answerDiv" hidden>
        <p>Number of remaining people: <span id="answerView"></span></p>
    </div>
</article>
{% endblock %}

{%load static%}
{% block scripts%}
<script type="text/javascript" src="{% static 'js/SimpleEvaluations.js' %}"></script>
{%endblock%}

Code/MuseumApp/museum/templates/museum/lab_task.html
{% extends "shared/layout.html" %}

{% block content %}

<form name="appearanceForm">
    <label>Text color</label>
    <div>
        <div>
            <label>Red</label>
            <input type="radio" name="text_color" value="red" onchange="changeTextColor()" />
        </div>
        <div>
            <label>Green</label>
            <input type="radio" name="text_color" value="green" onchange="changeTextColor()" />
        </div>
        <div>
            <label>Blue</label>
            <input type="radio" name="text_color" value="blue" onchange="changeTextColor()" />
        </div>
    </div>
    <label>background color</label>
    <div>
        <div>
            <label>Red</label>
            <input type="radio" name="background_color" value="red" onchange="changePageColor()" />
        </div>
        <div>
            <label>Green</label>
            <input type="radio" name="background_color" value="green" onchange="changePageColor()" />
        </div>
        <div>
            <label>Blue</label>
            <input type="radio" name="background_color" value="blue" onchange="changePageColor()" />
        </div>
    </div>
    <label>Text size</label>
    <div>
        <div>
            <label>Small</label>
            <input type="radio" name="text_size" value="small" onchange="changeTextSize()" />
        </div>
        <div>
            <label>Medium</label>
            <input type="radio" name="text_size" value="medium" onchange="changeTextSize()" />
        </div>
        <div>
            <label>Big</label>
            <input type="radio" name="text_size" value="big" onchange="changeTextSize()" />
        </div>
    </div>
</form>
<article>
    <h4>Introduction</h4>


    <br /><q cite=https://www.brainyquote.com/quotes/lyndon_b_johnson_157402> The noblest search is the search for excellence. </q> - Lyndon B. Johnson


    <blockquote cite="https://www.jfklibrary.org/learn/about-jfk/life-of-john-f-kennedy/john-f-kennedy-quotations#:~:text=For%20time%20and%20the%20world,Kennedy%2C%201963.">
        - John F. Kennedy
        But Goethe tells us in his greatest poem that Faust lost the liberty of his soul when he said to the passing moment:
        'Stay, thou art so fair.' And our liberty, too, is endangered if we pause for the passing moment, if we rest on our achievements,
        if we resist the pace of progress. For time and the world do not stand still. Change is the law of life. And those who look only to
        the past or the present are certain to miss the future.
    </blockquote>

</article>
<article translate="yes">
    <figure>
        <p style="position: relative;">
            Here are breathtaking poem
        </p>
        <article myatrr="poem">
            Eyes of grey -- a sodden quay,
            Driving rain and falling tears,
            As the steamer wears to sea
            In a parting storm of cheers.
            Sing, for Faith and Hope are high --
            None so true as you and I --
            Sing the Lovers' Litany:<wbr />
            "Love like ours can never die!"

        </article>
        <figcaption myatrr="poem_caption" style="position: relative;">
            Rudyard Kipling <i>"The Lovers' Litany"</i>
        </figcaption>
    </figure>

    <article>
        <p isBreak="break">
            SHtirlic igral v karty i proigralsya. No SHtirlic umel delat' horoshuyu minu pri plohoj igre. Kogda SHtirlic pokinul kompaniyu, mina srabotala.
        </p>
    </article>

</article>

<br />
<a href="http://google.com">GOOGLE.com</a>
<br />
<a href="http://yandex.ru">YANDEX.ru</a>
<br />

<video width="360" height="240"
       src="/media/videos/HD_Epic_Sax_Gandalf.mp4"
       autoplay controls preload="none" muted>
    Video cannot be displayed
</video>

<br />
<audio autoplay controls id="awesome_music" muted>
    <source src="/media/audio/expic_music.mp3" />
</audio>

<div>
    <a>
        <p class="task">
            Thats indirect descendant of div
        </p>
    </a>
    <p class="task2">
        Thats direct descendant of div
    </p>

</div>
<p>
    Thats not
</p>

<p>FR: <q lang="fr">(FR)To be or not to be</q></p>
<p>DE: <q lang="de">(FR)To be or not to be</q></p>
<p>EN: <q lang="en">(FR)To be or not to be</q></p>

<p class="greeteng">Gustavo</p>

<form>
    <div>
        <label>Disabled input</label>
        <input disabled />
    </div>
    <div>
        <label>Max value 5</label>
        <input type="number" max="5" />
    </div>

</form>

<iframe src="https://en.wikipedia.org/wiki/C%2B%2B" style="width:1000px; height:600px;"></iframe>
<br />
<br />
<code>
    print("Hello world!")
</code>
{% if user.is_superuser %}
<div>
    <label>Enter time of image change: </label>
    <input type="number" id="time" value="5" onchange="RestartCarousel()"/>
</div>
{% endif %}
<div class="carousel-container">
    <div class="carousel-slide">
        <a href="https://com.com"><img src="/media/icons/logos/com_logo.png" alt="1"></a>
    </div>
    <div class="carousel-slide">
        <a href="https://facebook.com"><img src="/media/icons/logos/facebook.png" alt="2"></a>
    </div>
    <div class="carousel-slide">
        <a href="https://twitter.com"><img src="/media/icons/logos/twitter.png" alt="3"></a>
    </div>
</div>


{% endblock %}

{%load static%}
{% block scripts%}
<script type="text/javascript" src="{% static 'js/DinamicAppearanceChange.js' %}"></script>
<script src="{% static 'js/carousel.js' %}"></script>
{%endblock%}

Code/MuseumApp/museum/templates/museum/review_detail.html
{% extends "shared/layout.html" %}

{% block content %}
<h1>{{ review.reviewer }}</h1>
<p>{{ review.rate }}</p>
<p>{{ review.text }}</p>
<p>{{ review.creation_date }}</p>
<a href="{% url 'review_delete' review.pk %}">Delete review</a>
{% endblock %}

Code/MuseumApp/museum/templates/museum/testExtends.html
{% extends "shared/layout.html" %}

{% block content %}

<h1>Its just for extends inheritance</h1>
{% endblock %}

{%load static%}
{% block scripts%}
<script type="text/javascript" src="{% static 'js/ExtendsInheritance.js' %}"></script>
{%endblock%}